server:
  forward-headers-strategy: FRAMEWORK

spring:
  liquibase:
    enabled: true
    change-log: classpath:/database/db.changelog-root.yml

  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB

  datasource:
    url: jdbc:h2:file:./h2/home-portal
    username: mv
    password: password


logging.level:
  org.ivcode: TRACE