mvn:
  root: ./mvn

  # Authorization parameters
  # security and user access
  auth:
    #auth type: Currently only supports "basic-auth-file"
    type: basic-auth-file

    # Admin credentials (optional)
    # This is used to create an admin. If an admin exists, it's not needed
    admin:
      username: admin
      password: password

  repositories:
    file-system:
      path: ${mvn.root}/www
