# Local Setup
#
# -= Docker-Compose =-
# cd ./scripts/dev && docker compose up -d
#
# -= Keycloak Logins =-
# URL: http://localhost:8081/auth/admin/
# Admin: admin/password
# User: user/password
#
# -= Oauth2 Setup =-
# Grant Type: authorization_code
# Authorization URL: http://localhost:8081/auth/realms/master/protocol/openid-connect/auth
# Token URL: http://localhost:8081/auth/realms/master/protocol/openid-connect/token
# Client ID: iv-mvn
# Client Secret: XKNTocHpUfEhTC01Ve1jyDec6DDtDOVD
# Redirect URI: http://localhost

server:
  port: 8080
  forward-headers-strategy: FRAMEWORK

spring:
  liquibase:
    enabled: true
    change-log: classpath:/database/db.changelog-root.yml

  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB

  # h2
# datasource:
#   url: jdbc:h2:file:./h2/mvn
#   username: mvn
#   password: password

  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/mvn?allowPublicKeyRetrieval=true
    username: mvn
    password: password

security:
  oauth2:
    admin: admin@domain.com
    issuer-url: http://localhost:8081/auth/realms/master

logging.level:
  org.ivcode: TRACE
