server:
  forward-headers-strategy: FRAMEWORK

spring:
  liquibase:
    enabled: true
    change-log: classpath:/database/db.changelog-root.yml

  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB

  # h2
# datasource:
#   url: jdbc:h2:file:./h2/mvn
#   username: mvn
#   password: password

  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/mvn?allowPublicKeyRetrieval=true
    username: mvn
    password: password

security:
  oauth2:
    admin: admin@domain.com
    issuer-url: http://localhost:8081/auth/realms/master

logging.level:
  org.ivcode: TRACE