mvn:

  # Authorization parameters
  # security and user access
  auth:
    #auth type: Currently only supports "basic-auth-file"
    type: basic-auth-file

    # if true, read operations are allowed by anyone
    public:
      snapshot: false
      release: true

    # Admin credentials (optional)
    # This is used to create an admin. If an admin exists, it's not needed
    admin:
      username: admin
      password: password

    # A basic auth implementation where users, roles, and password hashes are maintained in a file
    basic-auth-file:
      password-file: ./mvn/mvn.password


  # File Server parameters
  # hosts and serves files
  snapshot:
    # file-server type. Currently only supports "file-system"
    type: file-system

    file-system:
      repository: ./mvn/www/snapshot

  # File Server parameters
  # hosts and serves files
  release:
    # file-server type. Currently only supports "file-system"
    type: file-system

    # A file-system implementation of the file server
    file-system:
      repository: ./mvn/www/release
