mvn:
  type: file-system # supported types: file-system
  public: true      # if true, read operations are allowed by anyone
  admin:
    username: admin
    password: password
  file-system:
    password-file: ./mvn/mvn.password
    repository: ./mvn/www